[package]
name = "supaterm"
version = "0.2.1"
edition = "2024"

[dependencies]
lexical-core = { version = "1", features = ["write-integers", "std"], default-features = false, optional = true }
rustix = { version = "1", features = ["stdio", "termios"], optional = true }



[features]
full = ["raw_mode", "window_size", "alternate_screen", "cursor_controls", "erase_functions"]
nightly = []

raw_mode = ["rustix"]
window_size = ["rustix"]

alternate_screen = []
cursor_controls = ["lexical-core"]
erase_functions = ["lexical-core"]



[[example]]
name = "alternate_screen"
required-features = ["alternate_screen", "cursor_controls"]

[[example]]
name = "raw_mode"
required-features = ["raw_mode"]


[[bin]]
name = "log_input"
required-features = ["raw_mode"]