[package]
name = "supaterm"
version = "0.2.0"
edition = "2024"



[dependencies]
itoa = { version = "1", optional = true }
indexmap = { version = "2", features = ["std"], default-features = false, optional = true }
rustix = { version = "1", features = ["stdio", "termios"], optional = true }



[features]
full = ["raw_mode", "alternate_screen", "cursor_controls", "erase_functions", "drop_handling"]
nightly = []

drop_handling = ["indexmap"]
raw_mode = ["dep:rustix"]
window_size = ["dep:rustix"]

alternate_screen = []
cursor_controls = ["dep:itoa"]
erase_functions = ["dep:itoa"]



[[example]]
name = "alternate_screen"
required-features = ["alternate_screen", "cursor_controls", "drop_handling"]

[[example]]
name = "hello_world"
required-features = []

[[example]]
name = "raw_mode"
required-features = ["raw_mode"]


[[bin]]
name = "log_input"
required-features = ["raw_mode"]